# CMake generated Testfile for 
# Source directory: /mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib
# Build directory: /mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMakeLib.testArgumentParser "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testArgumentParser")
set_tests_properties(CMakeLib.testArgumentParser PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestBinPacker "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testCTestBinPacker")
set_tests_properties(CMakeLib.testCTestBinPacker PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestResourceAllocator "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testCTestResourceAllocator")
set_tests_properties(CMakeLib.testCTestResourceAllocator PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestResourceSpec "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testCTestResourceSpec" "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib")
set_tests_properties(CMakeLib.testCTestResourceSpec PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestResourceGroups "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testCTestResourceGroups")
set_tests_properties(CMakeLib.testCTestResourceGroups PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testGccDepfileReader "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testGccDepfileReader" "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib")
set_tests_properties(CMakeLib.testGccDepfileReader PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testGeneratedFileStream "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testGeneratedFileStream")
set_tests_properties(CMakeLib.testGeneratedFileStream PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testJSONHelpers "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testJSONHelpers")
set_tests_properties(CMakeLib.testJSONHelpers PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testRST "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testRST" "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib")
set_tests_properties(CMakeLib.testRST PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testRange "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testRange")
set_tests_properties(CMakeLib.testRange PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testOptional "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testOptional")
set_tests_properties(CMakeLib.testOptional PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testString "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testString")
set_tests_properties(CMakeLib.testString PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testStringAlgorithms "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testStringAlgorithms")
set_tests_properties(CMakeLib.testStringAlgorithms PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testSystemTools "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testSystemTools")
set_tests_properties(CMakeLib.testSystemTools PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUTF8 "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testUTF8")
set_tests_properties(CMakeLib.testUTF8 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testXMLParser "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testXMLParser")
set_tests_properties(CMakeLib.testXMLParser PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testXMLSafe "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testXMLSafe")
set_tests_properties(CMakeLib.testXMLSafe PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testFindPackageCommand "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testFindPackageCommand")
set_tests_properties(CMakeLib.testFindPackageCommand PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUVProcessChain "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testUVProcessChain" "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/testUVProcessChainHelper")
set_tests_properties(CMakeLib.testUVProcessChain PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUVRAII "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testUVRAII")
set_tests_properties(CMakeLib.testUVRAII PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUVStreambuf "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testUVStreambuf" "/mnt/c/users/efede/pico/cmake-3.19.4/bin/cmake")
set_tests_properties(CMakeLib.testUVStreambuf PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCMExtMemory "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testCMExtMemory")
set_tests_properties(CMakeLib.testCMExtMemory PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCMExtAlgorithm "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLibTests" "testCMExtAlgorithm")
set_tests_properties(CMakeLib.testCMExtAlgorithm PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;68;add_test;/mnt/c/users/efede/pico/cmake-3.19.4/Tests/CMakeLib/CMakeLists.txt;0;")
subdirs("PseudoMemcheck")
